# Guarneri-style device YAML configuration

# Objects only available at APS

apstools.devices.ApsMachineParametersDevice:
  - name: aps

id12_common.devices.dg645_delay_gen.SocketDG645DelayGen:
- name: dg645_idb # delay generator
  address: "10.54.122.66:5025"
  labels: [ "delaygen" ]
  trigger_source: "Single shot"  # 5

- name: dg645_idc # delay generator
  address: "10.54.122.104:5025"
  labels: [ "delaygen" ]
  trigger_source: "Single shot external rising edges"  # 3
