# Guarneri-style device YAML configuration

# Objects only available at APS

apstools.devices.ApsMachineParametersDevice:
- name: aps
  labels:
  - baseline

id12_common.devices.delays.DG645Delay:
- name: dg645  # 2025-06-11: Should be available after IOC is restarted.
  prefix: "12idc:DG1:"
  labels: [ "delaygen" ]

id12_common.devices.struck.Struck:
- name: struck
  prefix: "12idc:3820:"
  labels: [ "scalers", "detectors" ]
