# Guarneri-style device YAML configuration

# Objects only available at APS

apstools.devices.ApsMachineParametersDevice:
- name: aps
  labels:
  - baseline

id12_common.devices.delays.DG645Delay:
- name: dg645
  prefix: "12idb:DG1:"
  labels: [ "delaygen"]
